version: '2.0'
services:
  web:
    image: flask-web-app
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/flask_app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1

  redis:
    image: redis
